name: Trigger on PR Approval

on: [push]

# on:
#   pull_request:
#     types: [opened, reopened]
#   pull_request_review:
#     types: [submitted]

jobs:
  build_job:
    defaults:
      run:
        shell: bash -el {0}
    name: Build and Run Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          allow-softlinks: true
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
          show-channel-urls: true
          use-only-tar-bz2: true
      - name: Conda Setup
        run: |
          conda create --name mle-dev python=3.9 numpy matplotlib scipy scikit-learn pandas flake8 mlflow
          conda activate mle-dev

      - name: Build the package
        run: |
          pip install build
          python -m build
      - name: Install the package and run
        run: |
          cd dist
          pip install house_value_prediction-0.0.1-py3-none-any.whl
          cd ..
          cd scripts
          python -m main_script.py
