name: Deploy Docker Image

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for DockerHub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for DockerHub password

    - name: Pull the Docker image
      run: |
        docker pull farhana06/house_value_prediction:1.0.0  # Replace with your actual image name and tag

    - name: Run the Docker container
      run: |
        docker run -d -p 5000:5000 --name house_value_prediction_container farhana06/house_value_prediction:1.0.0
